# Generated by Django 5.2.4 on 2025-08-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_person_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
