name: Continuous Integration
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-test-and-sonar:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    
    - name: Install Dependencies
      run: |
        pip install uv
        make install
    
    - name: Run Linter
      run: |
        make lint

    - name: Run Tests
      run: |
        make test
    
    - name: Make test pytest
      run: make test-pytest
    
    - name: Make test pytest --coverage
      run: make test-coverage

    - name: SonarQubeScan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
        args: >
            -Dsonar.projectKey=sergeikuz_python-project-52
            -Dsonar.organization=sergeikuz
            -Dsonar.python.coverage.reportPaths=coverage.xml
